---
HOSTS:
  windows2016:
    box: win2016
    synced_folder: disabled
    platform: windows-2016-64
    packaging_platform: windows-2012-x64
    ruby_arch: x64
    hypervisor: vagrant
    user: vagrant
    vagrant_memsize: 4096
    vagrant_cpus: 2
    roles:
      - agent
CONFIG:
  nfs_server: none
  consoleport: 443
  log_level: verbose
  type: aio
